
/////////// BOOTSTRAP CODE ///////////

// SP = 256
@256
D=A
@SP
M=D

// call Sys.init
 // store return address

@SYS.INIT$ret.0
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store LCL address

@LCL
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store ARG address

@ARG
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THIS address

@THIS
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THAT address

@THAT
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // set new ARG location

@SP
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1 // ARG = SP - 5 - nArgs
@ARG
M=D // D register contains the new ARG address after assembly generated by complex_arith() was called
 // Set LCL to SP
@SP
D=M
@LCL
M=D
 // GOTO function
@SYS.INIT
0;JMP // jump to function
(SYS.INIT$ret.0) // return point

/////////// End of BOOTSTRAP CODE ///////////
              

// FUNCTION SYS.INIT 0
(SYS.INIT)

// PUSH CONSTANT 4000
@4000
D=A
@SP
A=M
M=D
@SP
M=M+1

// POP POINTER 0
@0
D=A
@THIS
D=D+A
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// PUSH CONSTANT 5000
@5000
D=A
@SP
A=M
M=D
@SP
M=M+1

// POP POINTER 1
@0
D=A
@THAT
D=D+A
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// CALL SYS.MAIN 0
 // store return address

@SYS.MAIN$ret.1
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store LCL address

@LCL
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store ARG address

@ARG
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THIS address

@THIS
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THAT address

@THAT
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // set new ARG location

@SP
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1 // ARG = SP - 5 - nArgs
@ARG
M=D // D register contains the new ARG address after assembly generated by complex_arith() was called
 // Set LCL to SP
@SP
D=M
@LCL
M=D
 // GOTO function
@SYS.MAIN
0;JMP // jump to function
(SYS.MAIN$ret.1) // return point

// POP TEMP 1
@1
D=A
@5
D=D+A
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// LABEL LOOP
(SYS.INIT$LOOP)

// GOTO LOOP
@SYS.INIT$LOOP
0;JMP

// FUNCTION SYS.MAIN 5
(SYS.MAIN)
@0
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

@0
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

@0
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

@0
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

@0
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

// PUSH CONSTANT 4001
@4001
D=A
@SP
A=M
M=D
@SP
M=M+1

// POP POINTER 0
@0
D=A
@THIS
D=D+A
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// PUSH CONSTANT 5001
@5001
D=A
@SP
A=M
M=D
@SP
M=M+1

// POP POINTER 1
@0
D=A
@THAT
D=D+A
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// PUSH CONSTANT 200
@200
D=A
@SP
A=M
M=D
@SP
M=M+1

// POP LOCAL 1
@1
D=A
@LCL
D=D+M
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// PUSH CONSTANT 40
@40
D=A
@SP
A=M
M=D
@SP
M=M+1

// POP LOCAL 2
@2
D=A
@LCL
D=D+M
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// PUSH CONSTANT 6
@6
D=A
@SP
A=M
M=D
@SP
M=M+1

// POP LOCAL 3
@3
D=A
@LCL
D=D+M
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// PUSH CONSTANT 123
@123
D=A
@SP
A=M
M=D
@SP
M=M+1

// CALL SYS.ADD12 1
 // store return address

@SYS.ADD12$ret.1
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store LCL address

@LCL
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store ARG address

@ARG
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THIS address

@THIS
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THAT address

@THAT
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // set new ARG location

@SP
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1 // ARG = SP - 5 - nArgs
@ARG
M=D // D register contains the new ARG address after assembly generated by complex_arith() was called
 // Set LCL to SP
@SP
D=M
@LCL
M=D
 // GOTO function
@SYS.ADD12
0;JMP // jump to function
(SYS.ADD12$ret.1) // return point

// POP TEMP 0
@0
D=A
@5
D=D+A
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// PUSH LOCAL 0
@0
D=A
@LCL
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// PUSH LOCAL 1
@1
D=A
@LCL
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// PUSH LOCAL 2
@2
D=A
@LCL
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// PUSH LOCAL 3
@3
D=A
@LCL
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// PUSH LOCAL 4
@4
D=A
@LCL
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// ADD
@SP
A=M
A=A-1
D=M
A=A-1
M=D+M
@SP
M=M-1

// ADD
@SP
A=M
A=A-1
D=M
A=A-1
M=D+M
@SP
M=M-1

// ADD
@SP
A=M
A=A-1
D=M
A=A-1
M=D+M
@SP
M=M-1

// ADD
@SP
A=M
A=A-1
D=M
A=A-1
M=D+M
@SP
M=M-1

// RETURN
 // Get return address

@LCL
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1
A=D
D=M // D now contains the return address
@R13
M=D // R13 now contains the return address

 // Repositions return value for the caller
@SP
A=M-1
D=M // D now contains the return value
@ARG
A=M
M=D // Set D (return value) into ARG's location

 // Reposition SP to ARG plus 1
@ARG
D=M // D now contains ARG's address
@SP
M=D+1

@LCL
D=M // store LCL's location into D. This is FRAME

@R14
M=D-1
A=M // set register to the address that holds the previous THAT's address
D=M // D contains the previous THAT's address
@THAT
M=D // rewrites THAT's location to the previous THAT's address

@R14
M=M-1
A=M // set register to the address that holds the previous THIS's address
D=M // D contains the previous THIS's address
@THIS
M=D // rewrites THIS's location to the previous THIS's address

@R14
M=M-1
A=M // set register to the address that holds the previous ARG's address
D=M // D contains the previous ARG's address
@ARG
M=D // rewrites THIS's location to the previous ARG's address

@R14
M=M-1
A=M // set register to the address that holds the previous LCL's address
D=M // D contains the previous LCL's address
@LCL
M=D // rewrites LCL's location to the previous LCL's address

@R13 // contains the return address
A=M
0;JMP // jumps to return address

// FUNCTION SYS.ADD12 0
(SYS.ADD12)

// PUSH CONSTANT 4002
@4002
D=A
@SP
A=M
M=D
@SP
M=M+1

// POP POINTER 0
@0
D=A
@THIS
D=D+A
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// PUSH CONSTANT 5002
@5002
D=A
@SP
A=M
M=D
@SP
M=M+1

// POP POINTER 1
@0
D=A
@THAT
D=D+A
@R13
M=D
@SP
M=M-1
A=M
D=M
@R13
A=M
M=D

// PUSH ARGUMENT 0
@0
D=A
@ARG
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// PUSH CONSTANT 12
@12
D=A
@SP
A=M
M=D
@SP
M=M+1

// ADD
@SP
A=M
A=A-1
D=M
A=A-1
M=D+M
@SP
M=M-1

// RETURN
 // Get return address

@LCL
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1
A=D
D=M // D now contains the return address
@R13
M=D // R13 now contains the return address

 // Repositions return value for the caller
@SP
A=M-1
D=M // D now contains the return value
@ARG
A=M
M=D // Set D (return value) into ARG's location

 // Reposition SP to ARG plus 1
@ARG
D=M // D now contains ARG's address
@SP
M=D+1

@LCL
D=M // store LCL's location into D. This is FRAME

@R14
M=D-1
A=M // set register to the address that holds the previous THAT's address
D=M // D contains the previous THAT's address
@THAT
M=D // rewrites THAT's location to the previous THAT's address

@R14
M=M-1
A=M // set register to the address that holds the previous THIS's address
D=M // D contains the previous THIS's address
@THIS
M=D // rewrites THIS's location to the previous THIS's address

@R14
M=M-1
A=M // set register to the address that holds the previous ARG's address
D=M // D contains the previous ARG's address
@ARG
M=D // rewrites THIS's location to the previous ARG's address

@R14
M=M-1
A=M // set register to the address that holds the previous LCL's address
D=M // D contains the previous LCL's address
@LCL
M=D // rewrites LCL's location to the previous LCL's address

@R13 // contains the return address
A=M
0;JMP // jumps to return address