
/////////// BOOTSTRAP CODE ///////////

// SP = 256
@256
D=A
@SP
M=D

// call Sys.init
 // store return address

@SYS.INIT$ret.0
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store LCL address

@LCL
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store ARG address

@ARG
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THIS address

@THIS
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THAT address

@THAT
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // set new ARG location

@SP
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1 // ARG = SP - 5 - nArgs
@ARG
M=D // D register contains the new ARG address after assembly generated by complex_arith() was called
 // Set LCL to SP
@SP
D=M
@LCL
M=D
 // GOTO function
@SYS.INIT
0;JMP // jump to function
(SYS.INIT$ret.0) // return point

/////////// End of BOOTSTRAP CODE ///////////
              

// FUNCTION MAIN.FIBONACCI 0
(MAIN.FIBONACCI)

// PUSH ARGUMENT 0
@0
D=A
@ARG
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// PUSH CONSTANT 2
@2
D=A
@SP
A=M
M=D
@SP
M=M+1

// LT
@SP
A=M
A=A-1
D=M
A=A-1

D=M-D
@EQ.0
D;JLT
@SP
A=M-1
A=A-1
M=0
@DN.0
0;JMP
(EQ.0)
@SP
A=M-1
A=A-1
M=-1
(DN.0)

@SP
M=M-1

// IF-GOTO N_LT_2
@SP
M=M-1
@SP
A=M
D=M
@MAIN.FIBONACCI$N_LT_2
D;JNE

// GOTO N_GE_2
@MAIN.FIBONACCI$N_GE_2
0;JMP

// LABEL N_LT_2
(MAIN.FIBONACCI$N_LT_2)

// PUSH ARGUMENT 0
@0
D=A
@ARG
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// RETURN
 // Get return address

@LCL
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1
A=D
D=M // D now contains the return address
@R13
M=D // R13 now contains the return address

 // Repositions return value for the caller
@SP
A=M-1
D=M // D now contains the return value
@ARG
A=M
M=D // Set D (return value) into ARG's location

 // Reposition SP to ARG plus 1
@ARG
D=M // D now contains ARG's address
@SP
M=D+1

@LCL
D=M // store LCL's location into D. This is FRAME

@R14
M=D-1
A=M // set register to the address that holds the previous THAT's address
D=M // D contains the previous THAT's address
@THAT
M=D // rewrites THAT's location to the previous THAT's address

@R14
M=M-1
A=M // set register to the address that holds the previous THIS's address
D=M // D contains the previous THIS's address
@THIS
M=D // rewrites THIS's location to the previous THIS's address

@R14
M=M-1
A=M // set register to the address that holds the previous ARG's address
D=M // D contains the previous ARG's address
@ARG
M=D // rewrites THIS's location to the previous ARG's address

@R14
M=M-1
A=M // set register to the address that holds the previous LCL's address
D=M // D contains the previous LCL's address
@LCL
M=D // rewrites LCL's location to the previous LCL's address

@R13 // contains the return address
A=M
0;JMP // jumps to return address

// LABEL N_GE_2
(MAIN.FIBONACCI$N_GE_2)

// PUSH ARGUMENT 0
@0
D=A
@ARG
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// PUSH CONSTANT 2
@2
D=A
@SP
A=M
M=D
@SP
M=M+1

// SUB
@SP
A=M
A=A-1
D=M
A=A-1
M=M-D
@SP
M=M-1

// CALL MAIN.FIBONACCI 1
 // store return address

@MAIN.FIBONACCI$ret.0
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store LCL address

@LCL
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store ARG address

@ARG
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THIS address

@THIS
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THAT address

@THAT
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // set new ARG location

@SP
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1 // ARG = SP - 5 - nArgs
@ARG
M=D // D register contains the new ARG address after assembly generated by complex_arith() was called
 // Set LCL to SP
@SP
D=M
@LCL
M=D
 // GOTO function
@MAIN.FIBONACCI
0;JMP // jump to function
(MAIN.FIBONACCI$ret.0) // return point

// PUSH ARGUMENT 0
@0
D=A
@ARG
A=D+M
D=M
@SP
A=M
M=D
@SP
M=M+1

// PUSH CONSTANT 1
@1
D=A
@SP
A=M
M=D
@SP
M=M+1

// SUB
@SP
A=M
A=A-1
D=M
A=A-1
M=M-D
@SP
M=M-1

// CALL MAIN.FIBONACCI 1
 // store return address

@MAIN.FIBONACCI$ret.1
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store LCL address

@LCL
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store ARG address

@ARG
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THIS address

@THIS
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THAT address

@THAT
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // set new ARG location

@SP
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1 // ARG = SP - 5 - nArgs
@ARG
M=D // D register contains the new ARG address after assembly generated by complex_arith() was called
 // Set LCL to SP
@SP
D=M
@LCL
M=D
 // GOTO function
@MAIN.FIBONACCI
0;JMP // jump to function
(MAIN.FIBONACCI$ret.1) // return point

// ADD
@SP
A=M
A=A-1
D=M
A=A-1
M=D+M
@SP
M=M-1

// RETURN
 // Get return address

@LCL
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1
A=D
D=M // D now contains the return address
@R13
M=D // R13 now contains the return address

 // Repositions return value for the caller
@SP
A=M-1
D=M // D now contains the return value
@ARG
A=M
M=D // Set D (return value) into ARG's location

 // Reposition SP to ARG plus 1
@ARG
D=M // D now contains ARG's address
@SP
M=D+1

@LCL
D=M // store LCL's location into D. This is FRAME

@R14
M=D-1
A=M // set register to the address that holds the previous THAT's address
D=M // D contains the previous THAT's address
@THAT
M=D // rewrites THAT's location to the previous THAT's address

@R14
M=M-1
A=M // set register to the address that holds the previous THIS's address
D=M // D contains the previous THIS's address
@THIS
M=D // rewrites THIS's location to the previous THIS's address

@R14
M=M-1
A=M // set register to the address that holds the previous ARG's address
D=M // D contains the previous ARG's address
@ARG
M=D // rewrites THIS's location to the previous ARG's address

@R14
M=M-1
A=M // set register to the address that holds the previous LCL's address
D=M // D contains the previous LCL's address
@LCL
M=D // rewrites LCL's location to the previous LCL's address

@R13 // contains the return address
A=M
0;JMP // jumps to return address

// FUNCTION SYS.INIT 0
(SYS.INIT)

// PUSH CONSTANT 4
@4
D=A
@SP
A=M
M=D
@SP
M=M+1

// CALL MAIN.FIBONACCI 1
 // store return address

@MAIN.FIBONACCI$ret.2
D=A // set the value in @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store LCL address

@LCL
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store ARG address

@ARG
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THIS address

@THIS
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // store THAT address

@THAT
D=M // set the value held by @value into D
@SP
A=M
M=D // push value onto stack
@SP
M=M+1 // increment stack pointer

 // set new ARG location

@SP
D=M
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1
D=D-1 // ARG = SP - 5 - nArgs
@ARG
M=D // D register contains the new ARG address after assembly generated by complex_arith() was called
 // Set LCL to SP
@SP
D=M
@LCL
M=D
 // GOTO function
@MAIN.FIBONACCI
0;JMP // jump to function
(MAIN.FIBONACCI$ret.2) // return point

// LABEL END
(None$END)

// GOTO END
@None$END
0;JMP